package opal.dev.wynnoverhaul.client

enum class MountMaterial(val displayName: String) {
    INGOT("Ingot"),
    GEM("Gem"),
    PLANK("Plank"),
    PAPER("Paper"),
    STRING("String"),
    GRAINS("Grains"),
    OIL("Oil"),
    MEAT("Meat"),
}

object MountFeedingData {
    val LEVELS = listOf(1, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 105, 110, 115)

    val STAT_KEYS = listOf("Speed", "Acceleration", "Altitude", "Energy", "Handling", "Toughness", "Boost", "Training")

    const val BREEDING_AVERAGE_LIMIT = 20

    val FEEDING_TIME: List<Triple<Int, Int, String>> = listOf(
        Triple(10, 1, "1 minute"),
        Triple(12, 5, "5 minutes"),
        Triple(13, 15, "15 minutes"),
        Triple(14, 30, "30 minutes"),
        Triple(15, 60, "1 hour"),
        Triple(16, 120, "2 hours"),
        Triple(17, 180, "3 hours"),
        Triple(18, 240, "4 hours"),
        Triple(19, 300, "5 hours"),
        Triple(20, 360, "6 hours"),
    )

    fun feedTimeFor(averageLimit: Int): Triple<Int, Int, String> =
        FEEDING_TIME.lastOrNull { it.first <= averageLimit } ?: FEEDING_TIME.first()

    val TABLE: Map<MountMaterial, Map<Int, Map<String, Int>>> = mapOf(
        MountMaterial.INGOT to mapOf(
            1 to mapOf("Energy" to 4, "Toughness" to 8),
            10 to mapOf("Energy" to 5, "Toughness" to 10),
            20 to mapOf("Energy" to 5, "Toughness" to 12),
            30 to mapOf("Energy" to 6, "Toughness" to 14),
            40 to mapOf("Energy" to 6, "Toughness" to 16),
            50 to mapOf("Energy" to 7, "Toughness" to 18),
            60 to mapOf("Energy" to 8, "Toughness" to 20),
            70 to mapOf("Energy" to 8, "Toughness" to 22),
            80 to mapOf("Energy" to 9, "Toughness" to 24),
            90 to mapOf("Energy" to 9, "Toughness" to 26),
            100 to mapOf("Energy" to 10, "Toughness" to 28),
            105 to mapOf("Energy" to 10, "Toughness" to 29),
            110 to mapOf("Energy" to 11, "Toughness" to 30),
            115 to mapOf("Energy" to 11, "Toughness" to 31),
        ),
        MountMaterial.GEM to mapOf(
            1 to mapOf("Speed" to 4, "Energy" to 2, "Training" to 6),
            10 to mapOf("Speed" to 5, "Energy" to 2, "Training" to 8),
            20 to mapOf("Speed" to 6, "Energy" to 3, "Training" to 9),
            30 to mapOf("Speed" to 6, "Energy" to 3, "Training" to 11),
            40 to mapOf("Speed" to 7, "Energy" to 3, "Training" to 12),
            50 to mapOf("Speed" to 8, "Energy" to 4, "Training" to 14),
            60 to mapOf("Speed" to 9, "Energy" to 4, "Training" to 15),
            70 to mapOf("Speed" to 10, "Energy" to 4, "Training" to 17),
            80 to mapOf("Speed" to 10, "Energy" to 4, "Training" to 18),
            90 to mapOf("Speed" to 11, "Energy" to 5, "Training" to 20),
            100 to mapOf("Speed" to 12, "Energy" to 5, "Training" to 21),
            105 to mapOf("Speed" to 12, "Energy" to 5, "Training" to 22),
            110 to mapOf("Speed" to 13, "Energy" to 5, "Training" to 23),
            115 to mapOf("Speed" to 13, "Energy" to 5, "Training" to 23),
        ),
        MountMaterial.PLANK to mapOf(
            1 to mapOf("Speed" to 2, "Acceleration" to 6, "Toughness" to 4),
            10 to mapOf("Speed" to 2, "Acceleration" to 8, "Toughness" to 5),
            20 to mapOf("Speed" to 3, "Acceleration" to 9, "Toughness" to 6),
            30 to mapOf("Speed" to 3, "Acceleration" to 11, "Toughness" to 6),
            40 to mapOf("Speed" to 3, "Acceleration" to 12, "Toughness" to 7),
            50 to mapOf("Speed" to 4, "Acceleration" to 14, "Toughness" to 8),
            60 to mapOf("Speed" to 4, "Acceleration" to 15, "Toughness" to 9),
            70 to mapOf("Speed" to 4, "Acceleration" to 17, "Toughness" to 10),
            80 to mapOf("Speed" to 4, "Acceleration" to 18, "Toughness" to 10),
            90 to mapOf("Speed" to 5, "Acceleration" to 20, "Toughness" to 11),
            100 to mapOf("Speed" to 5, "Acceleration" to 21, "Toughness" to 12),
            105 to mapOf("Speed" to 5, "Acceleration" to 22, "Toughness" to 12),
            110 to mapOf("Speed" to 5, "Acceleration" to 23, "Toughness" to 13),
            115 to mapOf("Speed" to 5, "Acceleration" to 23, "Toughness" to 13),
        ),
        MountMaterial.PAPER to mapOf(
            1 to mapOf("Altitude" to 8, "Boost" to 4),
            10 to mapOf("Altitude" to 10, "Boost" to 5),
            20 to mapOf("Altitude" to 12, "Boost" to 5),
            30 to mapOf("Altitude" to 14, "Boost" to 6),
            40 to mapOf("Altitude" to 16, "Boost" to 6),
            50 to mapOf("Altitude" to 18, "Boost" to 7),
            60 to mapOf("Altitude" to 20, "Boost" to 8),
            70 to mapOf("Altitude" to 22, "Boost" to 8),
            80 to mapOf("Altitude" to 24, "Boost" to 9),
            90 to mapOf("Altitude" to 26, "Boost" to 9),
            100 to mapOf("Altitude" to 28, "Boost" to 10),
            105 to mapOf("Altitude" to 29, "Boost" to 10),
            110 to mapOf("Altitude" to 30, "Boost" to 11),
            115 to mapOf("Altitude" to 31, "Boost" to 11),
        ),
        MountMaterial.STRING to mapOf(
            1 to mapOf("Acceleration" to 2, "Handling" to 4, "Boost" to 6),
            10 to mapOf("Acceleration" to 2, "Handling" to 5, "Boost" to 8),
            20 to mapOf("Acceleration" to 3, "Handling" to 6, "Boost" to 9),
            30 to mapOf("Acceleration" to 3, "Handling" to 6, "Boost" to 11),
            40 to mapOf("Acceleration" to 3, "Handling" to 7, "Boost" to 12),
            50 to mapOf("Acceleration" to 4, "Handling" to 8, "Boost" to 14),
            60 to mapOf("Acceleration" to 4, "Handling" to 9, "Boost" to 15),
            70 to mapOf("Acceleration" to 4, "Handling" to 10, "Boost" to 17),
            80 to mapOf("Acceleration" to 4, "Handling" to 10, "Boost" to 18),
            90 to mapOf("Acceleration" to 5, "Handling" to 11, "Boost" to 20),
            100 to mapOf("Acceleration" to 5, "Handling" to 12, "Boost" to 21),
            105 to mapOf("Acceleration" to 5, "Handling" to 12, "Boost" to 22),
            110 to mapOf("Acceleration" to 5, "Handling" to 13, "Boost" to 23),
            115 to mapOf("Acceleration" to 5, "Handling" to 13, "Boost" to 23),
        ),
        MountMaterial.GRAINS to mapOf(
            1 to mapOf("Speed" to 8, "Altitude" to 4),
            10 to mapOf("Speed" to 10, "Altitude" to 5),
            20 to mapOf("Speed" to 12, "Altitude" to 5),
            30 to mapOf("Speed" to 14, "Altitude" to 6),
            40 to mapOf("Speed" to 16, "Altitude" to 6),
            50 to mapOf("Speed" to 18, "Altitude" to 7),
            60 to mapOf("Speed" to 20, "Altitude" to 8),
            70 to mapOf("Speed" to 22, "Altitude" to 8),
            80 to mapOf("Speed" to 24, "Altitude" to 9),
            90 to mapOf("Speed" to 26, "Altitude" to 9),
            100 to mapOf("Speed" to 28, "Altitude" to 10),
            105 to mapOf("Speed" to 29, "Altitude" to 10),
            110 to mapOf("Speed" to 30, "Altitude" to 11),
            115 to mapOf("Speed" to 31, "Altitude" to 11),
        ),
        MountMaterial.OIL to mapOf(
            1 to mapOf("Altitude" to 2, "Handling" to 6, "Training" to 4),
            10 to mapOf("Altitude" to 2, "Handling" to 8, "Training" to 5),
            20 to mapOf("Altitude" to 3, "Handling" to 9, "Training" to 6),
            30 to mapOf("Altitude" to 3, "Handling" to 11, "Training" to 6),
            40 to mapOf("Altitude" to 3, "Handling" to 12, "Training" to 7),
            50 to mapOf("Altitude" to 4, "Handling" to 14, "Training" to 8),
            60 to mapOf("Altitude" to 4, "Handling" to 15, "Training" to 9),
            70 to mapOf("Altitude" to 4, "Handling" to 17, "Training" to 10),
            80 to mapOf("Altitude" to 4, "Handling" to 18, "Training" to 10),
            90 to mapOf("Altitude" to 5, "Handling" to 20, "Training" to 11),
            100 to mapOf("Altitude" to 5, "Handling" to 21, "Training" to 12),
            105 to mapOf("Altitude" to 5, "Handling" to 22, "Training" to 12),
            110 to mapOf("Altitude" to 5, "Handling" to 23, "Training" to 13),
            115 to mapOf("Altitude" to 5, "Handling" to 23, "Training" to 13),
        ),
        MountMaterial.MEAT to mapOf(
            1 to mapOf("Acceleration" to 4, "Energy" to 8),
            10 to mapOf("Acceleration" to 5, "Energy" to 10),
            20 to mapOf("Acceleration" to 5, "Energy" to 12),
            30 to mapOf("Acceleration" to 6, "Energy" to 14),
            40 to mapOf("Acceleration" to 6, "Energy" to 16),
            50 to mapOf("Acceleration" to 7, "Energy" to 18),
            60 to mapOf("Acceleration" to 8, "Energy" to 20),
            70 to mapOf("Acceleration" to 8, "Energy" to 22),
            80 to mapOf("Acceleration" to 9, "Energy" to 24),
            90 to mapOf("Acceleration" to 9, "Energy" to 26),
            100 to mapOf("Acceleration" to 10, "Energy" to 28),
            105 to mapOf("Acceleration" to 10, "Energy" to 29),
            110 to mapOf("Acceleration" to 11, "Energy" to 30),
            115 to mapOf("Acceleration" to 11, "Energy" to 31),
        ),
    )
}
